# [target.'cfg(all(windows, target_env = "msvc"))']
# rustflags = ["-C", "target-feature=+crt-static"]
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = [
    "-C", "target-feature=+crt-static",
]
[target.'cfg(all(windows, target_env = "gnu"))']
rustflags = [
    "-C", "target-feature=+crt-static",
]